all: fcfs rr srtf hpf

fcfs:
	g++ -Wall -o fcfs fcfs.cc Jobs.cpp

rr:
	g++ -Wall -o rr rr.cc Jobs.cpp

srtf:
	g++ -Wall -o srtf srtf.cc Jobs.cpp

hpf:
	g++ -Wall -o hpf hpf.cc Jobs.cpp

clean:
	rm fcfs rr srtf hpf
